from typing import Protocol
from .models import MemoryItem


class MemoryStore(Protocol):
    def add(self, item: MemoryItem) -> None: ...
    def get(self, item_id: str) -> MemoryItem | None: ...
    def delete(self, item_id: str) -> bool: ...
    def list(self) -> list[MemoryItem]: ...
